### ISSUE TITLE
No compatible version found: lws@~0.2.1

### ISSUE THREAD

**Issue by yqrashawn** [avoidwork/rozu#22]
npm ERR! No compatible version found: lws@~0.2.1
npm ERR! Valid install targets:
npm ERR! 2.0.0-0, 0.0.1-security

**Comment by avoidwork** [comment]
I'll spin up a new version in my evening using the newest `tenso` which uses `uws`, as `lws` was deprecated & removed by the author.

**Comment by avoidwork** [comment]
Hi, this should be a drop in replacement based on the documentation. This is an older version of tenso, so I'll probably release a new major version soon which moves to node.js 6.0+
